Merge Product info into main
hackreactor-lax45-frontendcapstone/project-catwalk pull request #11
Opened 2021-07-26 20:26 UTC by dlthfl87

- Refactored product summary, description from class to functional component
- Rendered product info from redux state
- Added sale price to page and style changes to price feature when product contains sale price

2021-07-26 22:14 UTC, lawlorseanr requested changes

2021-07-26 22:14 UTC, lawlorseanr commented on client/src/components/Overview/ProductSummary.jsx
> +  if (styleInfo && !styleInfo.price.sale_price) {
You could combine this call to useSelector with the next call to usesSelector:

```suggestion
  const state = useSelector(state => {
    if (state.product.styleInfo.results === undefined) {
      return undefined;
    }
    return {
      productInfo: state.product.productInfo,
      price: state.product.styleInfo.results[state.style].price
    };
  });
  
  if (!state) {
    return (<div>Loading...</div>);
  }
  return (
    ...
```

Then your calls later would be simplified to e.g., price.original_price instead of styleInfo.price.original_price.

2021-07-26 22:14 UTC, lawlorseanr commented on client/src/components/Overview/ProductSummary.jsx
> +        <div id="body-overview-price">${styleInfo.price.original_price} USD</div>
It would be better to have only one block of code here instead of two nearly identical blocks. The only thing that is changing is the price info based on whether the .sale_price is equal to null or not. You could use a helper function like:

```javascript
const priceHelper = (price) =>  {
if (price.sale_price === null) {
  return (<div id="body-overview-price">${price.original_price} USD</div>);
} else {
  return (
    <div id="body-overview-oldprice">${price.original_price} USD</div>
    <div id="body-overview-saleprice">${price.sale_price} USD</div>
  );
} 
```

```suggestion
        {priceHelper(price)}
```

And if you do that you don't  need the if statements, you can have just one block of code that you return.

2021-07-26 22:14 UTC, lawlorseanr commented on client/src/components/Overview/ProductSummary.jsx
>    }
This else could be removed in favor of returning some "loading" div if state does not exist yet, as suggested above.

2021-07-26 23:41 UTC, dlthfl87 commented on client/src/components/Overview/ProductSummary.jsx
> +  if (styleInfo && !styleInfo.price.sale_price) {
In this case, I still need state.price to specify the key in state that I need.

2021-07-26 23:46 UTC, lawlorseanr commented on client/src/components/Overview/ProductSummary.jsx
> +  if (styleInfo && !styleInfo.price.sale_price) {
Line 15 of the suggested change pulls out the price info for use in the other parts of your code.

2021-07-26 23:48 UTC, lawlorseanr commented
@dlthfl87 make sure your tests pass before committing

2021-07-26 23:58 UTC, lawlorseanr requested changes

2021-07-26 23:58 UTC, lawlorseanr commented on client/src/components/Overview/ProductSummary.jsx
> +  const priceHelper = (style) => {
I don't think this input variable should be named "style." "Price" would be more accurate.

2021-07-26 23:58 UTC, lawlorseanr commented on client/src/components/Overview/ProductSummary.jsx
> +          <div id="body-overview-saleprice">${style.sale_price} USD</div>
```suggestion
  const priceHelper = (price) => {
    if (price.sale_price === null) {
      return (<div id="body-overview-price">${price.original_price} USD</div>);
    } else {
      return (
        <div>
          <div id="body-overview-oldprice">${price.original_price} USD</div>
          <div id="body-overview-saleprice">${price.sale_price} USD</div>
```

2021-07-26 23:58 UTC, lawlorseanr commented on __tests__/overview-product-summary.test.js
> +import ProductSummary from '../client/src/components/Overview/ProductSummary.jsx';
Not sure what happened, but something broke here.

2021-07-27 00:33 UTC, dlthfl87 commented on __tests__/overview-product-summary.test.js
> +import ProductSummary from '../client/src/components/Overview/ProductSummary.jsx';
I commented it out for now. I cannot use the import statement without installing babel - jest package.

2021-07-27 03:07 UTC, merged